# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-LDAP-HTMLWidget
version:      0.04
version_from: lib/Net/LDAP/HTMLWidget.pm
installdirs:  site
requires:
    HTML::Widget:                  1.11
    Net::LDAP:                     0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
